DESC EMP; --describe 뜻 설명
SELECT*FROM EMP;
DESC EMP;
DESC DEPT;
DESC SALGRADE;
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO FROM EMP;
SELECT DISTINCT DEPTNO FROM EMP; -- 중복제거
SELECT ALL JOB, DEPTNO FROM EMP;
SELECT ENAME, JOB, SAL, COMM FROM EMP;
SELECT DEPTNO, DNAME, LOC FROM DEPT;
SELECT ENAME, SAL, SAL*12+COMM, COMM FROM EMP;
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO FROM EMP;
desc member;
SELECT * FROM USERLIST;
SELECT DISTINCT SAL FROM EMP;
SELECT SAL FROM EMP;
SELECT * FROM EMP ORDER BY SAL DESC; -- descending 뜻 내림차순